# Cloud Build configuration for building and deploying Shortly
options:
  # Send build logs only to Cloud Logging (no GCS bucket needed)
  logging: CLOUD_LOGGING_ONLY
steps:
  # 1. Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/shortly', '.']

  # 2. Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud run deploy shortly \
          --image=gcr.io/$PROJECT_ID/shortly \
          --region=us-central1 \
          --platform=managed \
          --allow-unauthenticated \
          --update-env-vars=DATABASE_URL="postgresql+psycopg2://postgres:$(gcloud secrets versions access latest --secret=shortly-db-pass)@/shortly?host=/cloudsql/$PROJECT_ID:us-central1:shortly-sql" \
          --add-cloudsql-instances=$PROJECT_ID:us-central1:shortly-sql

# Declare the built Docker image so Cloud Build will automatically push it
images:
  - 'gcr.io/$PROJECT_ID/shortly'